### ISSUE TITLE
Support Chromium

### ISSUE THREAD

**Issue by dbrekelmans** [dbrekelmans/browser-driver-installer#2]
In order to support Chromium, a few things need to happen:
- Create `src/Browser/Chromium/PathResolver`
- Create `src/Browser/Chromium/VersionResolver`
- Register pathresolver to factory in `install.php`
- Register versionresolver to factory in `install.php`

Chromium can work with the already existing ChromeDriver.

As an example, you can look at how GoogleChrome is implemented.

**Comment by laurent35240** [comment]
Hi

FYI I started to work on Chromium support in PR #32 
This is still work in progress because I need to handle properly case when we need to download dev chromedriver for chromium. They are not located then on https://chromedriver.storage.googleapis.com but on https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html

**Comment by laurent35240** [comment]
So I finished this PR by deciding to then download Beta ChromeDriver in case of handling with Chrome/Chromium coming from dev or canary channel. 
It is what is advised on this page https://chromedriver.chromium.org/downloads/version-selection

I see that now checks are failing on composer part. It seems that is due to some incompatibility with Composer 2. Probably better to deal with that on separated PR
