### ISSUE TITLE
dbrekelmans/bdi is marked as ^7.2 satisfable but .phar archive contains vendor of symfony that requires 8.0 at least

### ISSUE THREAD

**Issue by 6562680** [dbrekelmans/browser-driver-installer#97]
(the point)

Am using 7.2 on legacy project and 1.0.7 of bdi is not working because phar contains code with ??= operators

**Comment by dbrekelmans** [comment]
Hi @6562680, you're right. It looks like the wrong dependency versions were installed while building the PHAR.

It would take considerable effort to create a release for an older version to resolve this. Since we dropped support for PHP 7.2, I don't see this happening.

You can try to run an older version of the PHAR.
If that doesn't work, you could install the dependencies and run the code directly: https://github.com/dbrekelmans/browser-driver-installer/tree/1.0.7.
You could also build your own PHAR from this tag.

**Comment by 6562680** [comment]
Good job here.
Already learned thanks to you how to build phar, how to dont use phar, how to resolve several php versions issues, how to build phar with humbug/box or with native instruments... Why not, it was an just library.

Btw the library does only "browser.exe --version" and then "wget driver_version.exe". 2 commands. For PHAR archive with 2MB of code.

And yes, you're hiding the exceptions on command detect, and dont split types of errors there. So casual error like "unable to get version" (that must be thrown as runtime) hidden in one row with other non-exception errors because you're inside foreach. Please, inspect Fowlers article about exception use cases.

In short, if something have to be catched - its not an exception. Exception should be marker that developer do something wrong (Logic) and program cannot solve error that is happened at runtime (Runtime). So validation and process, 2 types of errors.

Once you working with mass-processing (any foreach use case) you have to collect errors to error bag and throw something like "AggregateException" or just output errors to the console.

In 1.0.7 code i saw something like try/catch inside the command ignoring that the symfony/application has own feature "catch exceptions" that could be disabled or enabled. Instead - you catch it own way and just ignore to continue foreach. That was awesome experience...

**Comment by dbrekelmans** [comment]
If you are unhappy with the tool that I built in my free time, you are not required to use it.

Feel free to open PRs for any improvements you have in mind.
